name: docker_check

on: [pull_request, push]
jobs:
    docker:
        runs-on: ubuntu-latest
        services:
          registry:
            image: registry:2
            ports:
              - 5000:5000
        steps:
            - uses: actions/checkout@v4
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag dj_exercises:$(date +%s)
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                driver-opts: network=host
            - name: Build
              uses: docker/build-push-action@v5
              with:
                context: .
                load: true
                tags: dj_exercises:$(date +%s)
            - name: Inspect
              run: |
                docker image inspect dj_exercises:$(date +%s)
