name: docker_check

on: [pull_request, push]
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag ${github.event.repository.name}:$(date +%s)
